### ISSUE TITLE
Building documentation locally

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1216]
I've tried to build the documentation locally, and get the error below. What Clang version should I use? I have

> clang -v
Ubuntu clang version 14.0.0-1ubuntu1

> julia --project=. make.jl
  Activating project at `~/HiGHS/docs`
    Updating registry at `~/.julia/registries/General.toml`
ERROR: LoadError: Unsatisfiable requirements detected for package Clang [40e3b903]:
 Clang [40e3b903] log:
 ├─possible versions are: 0.7.0-0.17.3 or uninstalled
 ├─restricted to versions 0.14 by an explicit requirement, leaving only versions 0.14.0-0.14.1
 └─restricted by julia compatibility requirements to versions: [0.7.0-0.9.2, 0.16.0-0.17.3] or uninstalled — no versions left
S

**Comment by odow** [comment]
What version of Julia do you have installed?

**Comment by odow** [comment]
```Julia
(base) oscar@Oscars-MBP HiGHS % julia --project=docs docs/make.jl 
  Activating environment at `~/Documents/Code/HiGHS/docs/Project.toml`
[ Info: Parsing headers...
/Users/oscar/Documents/Code/HiGHS/src/util/HighsInt.h:27:10: fatal error: 'HConfig.h' file not found
/Users/oscar/Documents/Code/HiGHS/src/util/HighsInt.h:27:10: fatal error: 'HConfig.h' file not found
[ Info: Processing header: /Users/oscar/Documents/Code/HiGHS/src/interfaces/highs_c_api.h
[ Info: Processing header: /Users/oscar/Documents/Code/HiGHS/src/util/HighsInt.h
[ Info: Building the DAG...
[ Info: Emit Julia expressions...
[ Info: [ProloguePrinter]: print to docs/c_api_gen/libhighs.jl
[ Info: [GeneralPrinter]: print to docs/c_api_gen/libhighs.jl
[ Info: [EpiloguePrinter]: print to docs/c_api_gen/libhighs.jl
[ Info: Done!
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
┌ Warning: Documenter could not auto-detect the building environment Skipping deployment.
└ @ Documenter ~/.julia/packages/Documenter/H5y27/src/deployconfig.jl:75
(base) oscar@Oscars-MBP HiGHS % julia --project=docs             
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.7 (2022-07-19)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(docs) pkg> st
      Status `~/Documents/Code/HiGHS/docs/Project.toml`
  [40e3b903] Clang v0.14.1
  [e30172f5] Documenter v0.27.24

shell> cat docs/Project.toml
[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Clang = "0.14"
```

**Comment by jajhall** [comment]
> What version of Julia do you have installed?

>julia -v
julia version 1.8.5

**Comment by odow** [comment]
Urgh. This should have worked on all Julia versions. Let me see if I can fix.

**Comment by odow** [comment]
Fixed. I just needed to tweak the compat: https://github.com/ERGO-Code/HiGHS/pull/1217

**Comment by odow** [comment]
Closed by #1217

**Comment by jajhall** [comment]
Nearly there. I still get

> ERROR: LoadError: SystemError: opening file "docs/c_api_gen/libhighs.jl": No such file or directory
Stacktrace:

How do I generate this?

Also (less seriously?)

> ⌅ [0ee61d77] + Clang_jll v13.0.1+3
 
>        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`

**Comment by odow** [comment]
> ERROR: LoadError: SystemError: opening file "docs/c_api_gen/libhighs.jl": No such file or directory

Ah. You need to build the docs from the root directory. Let me see if I can improve, and I'll update the README with better instructions.

**Comment by odow** [comment]
Third time lucky? How about with https://github.com/ERGO-Code/HiGHS/pull/1219

**Comment by jajhall** [comment]
Yes, that works for me `HighsInt.h` isn't finding `HConfig.h`, but it doesn't seem to matter
