### ISSUE TITLE
Could not find METIS_PATH using the following files: metis.h

### ISSUE THREAD

**Issue by jschueller** [ERGO-Code/HiGHS#2618]
when METIS_ROOT is not specified, cmake is not allowed to look into default directories, which prevents from detecting a system installation, without any alternative:

```
if(metis_FOUND)
    message(STATUS "metis CMake config path: ${metis_DIR}")
else()
    find_path(METIS_PATH
        NAMES "metis.h"
        REQUIRED
        PATHS "${METIS_ROOT}/include"
        NO_DEFAULT_PATH)                            <==================== here

    message(STATUS "Found Metis header at ${METIS_PATH}")

    find_library(METIS_LIB
        NAMES metis libmetis
        REQUIRED
        PATHS "${METIS_ROOT}/lib" "${METIS_ROOT}/bin"
        NO_DEFAULT_PATH)                            <==================== here
```
this is on archlinux (metis cmake configuration file is not available), with highs 1.12.0

**Comment by galabovaa** [comment]
Addressed in https://github.com/ERGO-Code/HiGHS/pull/2620. 

Could you double check if you get any further issues with the METIS_PATH?

**Comment by jschueller** [comment]
I would expect to not have to set anything since all my libs are in default paths, currently if I dont set any path even METIS_ROOT I get:
 
```
$ cd HiGHS && cmake -DHIPO=ON -DCMAKE_UNITY_BUILD=ON -DBLA_VENDOR=Generic
- METIS_ROOT is 
CMake Error at cmake/FindHipoDeps.cmake:154 (find_path):
  Could not find METIS_PATH using the following files: metis.h
Call Stack (most recent call first):
  CMakeLists.txt:195 (include)


-- Configuring incomplete, errors occurred!
The command '/bin/sh -c cd HiGHS && cmake -DHIPO=ON -DCMAKE_UNITY_BUILD=ON -DBLA_VENDOR=Generic -DZMETIS_PATH=/usr -B build . && make -C build' returned a non-zero code: 1
```

**Comment by galabovaa** [comment]
I see, I pushed another fix for that to latest. Would you please try the code from out latest branch again?

**Comment by jschueller** [comment]
now I get another error:
```
Make Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/runner/work/hello-highs/hello-highs/HiGHS/highs/METIS_PATH
   used as include directory in directory /home/runner/work/hello-highs/hello-highs/HiGHS/highs
METIS_LIB
```

I reused my repo https://github.com/jschueller/hello-highs to test this, and it still fails even on ubuntu, see hipo branch (and github action log)

**Comment by jschueller** [comment]
I think you could use only one find_path for metis.h and one find_library for metis lib if the path formed by METIS_ROOT would be provided as HINT, regardless of whether METIS_ROOT is provided or not

**Comment by galabovaa** [comment]
OK, thank you for reproducing it in your repo, I will look into it further

**Comment by galabovaa** [comment]
A stripped, modified Metis is now part of the HiGHS code, so METIS ROOT is removed all together in the latest branch, and metis is no longer a dependency which should be installed separately.

**Comment by jschueller** [comment]
so its not possible to use an external METIS lib instead ?

**Comment by jajhall** [comment]
> so its not possible to use an external METIS lib instead ?

No, this simplifies things for us, both in terms of packaging and support.
